spring.application.name=UniInternPortal

spring.datasource.url=jdbc:postgresql://localhost:5432/uniintern
spring.datasource.username=uniadmin
spring.datasource.password=Uniintern@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8089

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG

# Mail Configuration (Example using Google SMTP, replace with actual SMTP credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kavindyaperera06@gmail.com
spring.mail.password=bgzskzdclwutypmc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
